/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl.ui.contentassist

import org.moflon.tgg.mosl.ui.contentassist.AbstractTGGProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TGGProposalProvider extends AbstractTGGProposalProvider {
}
