/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TGGRuntimeModule extends org.moflon.tgg.mosl.AbstractTGGRuntimeModule {

}
